### ISSUE TITLE
Demo code (demo.py) not working: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' 

### ISSUE THREAD

**Issue by marisancans** [Ryan-prime/3DG-STFM#3]
Demo code not working, steps I did
git clone repo
conda env create -f environment.yaml
conda activate stfm
pip install torch einops yacs kornia

downloaded models from https://drive.google.com/file/d/1S5uscMp-3el4AUALQJznG1lyN-_O4Ks7/view

python demo.py - spits out error :(

```
Exception has occurred: ImportError
cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/home/ma/anaconda3/envs/stfm/lib/python3.8/site-packages/torchmetrics/utilities/data.py)
  File "/mnt/data/src/3DG-STFM/demo.py", line 81, in <module>
    sd = torch.load(pretrained_ckpt, map_location='cpu')['state_dict']
```

**Comment by marisancans** [comment]
Looks like the problem is library related, not this repo

**Comment by YznMur** [comment]
Downgrade torchmetrics to v0.6.0
```
pip install torchmetrics==0.6.0
```
